name: flutter_mvc
description: Base Flutter MVC application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  provider: ^3.0.0

  http: ^0.12.1

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:

  gen_lang: 0.1.3

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
